### ISSUE TITLE
Unable to use plugin

### ISSUE THREAD

**Issue by Villain-GH** [awe-source/OctoPrint-SkipTo#1]
![image](https://github.com/user-attachments/assets/02732e51-27d8-4c3c-8866-8db96f79e60d)
Upon entering a value, nothing happens. It will stay at Layer #0/Z=0
Unable to resume print.

Unable to save any settings with plugin enabled.
![image](https://github.com/user-attachments/assets/abf3baf5-5dbc-460f-b856-7c580ac72141)

**Comment by designnotdrum** [comment]
Same issue for me.

**Comment by awe-source** [comment]
Hmm... my bad (thx for trying and reporting tho!)

Okay... it's a side effect of the issues in re-jigging version stuff for sharing... upper lower case stuff...
Hopefully this fixes it 0..1.2...

no nevermind that... I'll re-create 0.1.1...

**Comment by awe-source** [comment]
dont fully understand how the OctoP plugin system actually works... but at a guess "goto plugin manager, "bin" it, close, (maybe "restart" dialog means you need to restart...), and then add it again...

If it doesn't work (caching or something) then I'll go the 0.1.2 route... let me know.

**Comment by awe-source** [comment]
okay there was also a problem with spaces in file names.
That shoudl be fixed too

**Comment by awe-source** [comment]
Hopefullly this is fixed now, but let me know if its still bad

**Comment by Villain-GH** [comment]
Can confirm it now appears to work, I just need to figure out how to skip homing now haha.

**Comment by awe-source** [comment]
Yeah a todo was don’t home or make sure the home+z move was modified to be higher than the new first layer… so it doesn’t knock stuff over

If you think that’s a good option… 
Or some combo of that…
Lemme know

**Comment by Villain-GH** [comment]
That would be highly useful! Could make resuming prints a breeze.
