### ISSUE TITLE
extrudes a lot

### ISSUE THREAD

**Issue by fabreu249PT** [awe-source/OctoPrint-SkipTo#4]
when arrives the position, starts extrudes a lot  (because the extruder is G91), my machine is delta, maybe if "reset" the extruder works

**Comment by awe-source** [comment]
I'm not sure what this means? 

Is g91 a machine name or dos your file use relative positioning? 

Can you share the output file? Or before and after?

**Comment by fabreu249PT** [comment]
I'm not explained the better way, my file use absolute positioning, i thought the extruder use relative positioning(G91) but no, use absolute and from time to time use G92 to zero the extruded length, when i skip to the point i want, read the Extruder value (E1171) and extrudes, what can i do to use the command the right way?
[cap_mos_grand_skipTo_z-height_8.7.zip](https://github.com/user-attachments/files/18053861/cap_mos_grand_skipTo_z-height_8.7.zip)

**Comment by awe-source** [comment]
a) thanks for the file I've taken a look, but aside from the same crazy "E1171" entry, I can't see how it "got here", can you provide the source file as well? We don't know much about delta machines in 'practice' either, apart from info in the GCODE specification, so if you have any model/specific info

b) we've just uploaded a new version that may help... maybe

UPDATE:
Nevermind - this is the issue...

In G-code, extruders can operate in two modes: absolute mode (M82) or relative mode (M83). IN this scenario the extruder is operating in absolute mode, see the code snip below, where the extrusion values are cumulative from the start of the print.

If you resume printing partway through a job without accounting for this, the printer might attempt to extrude the total amount calculated from the beginning of the print, causing excessive extrusion. To address this, is challenging...

We'd need to adjust the extrusion value for the point at which you resume printing.

M82 ;absolute extrusion mode <-- not so good... 
;---------------------------------------
;Deltacomb start script
;---------------------------------------
G21 ;metric values
G90 ;absolute positioning <-- good and supported

With THIS plugin as it stands to support this, we would need to modify ALL THE E values to something like (E minus the STARTING LAYERS ALREADY USED VALUE (so for your file minus 1171 from (all?) e values...

*(YOU could perhaps do this in a regex if you really need to get through this... right now)

as for supporting this, I'm not sure - currently it just throws a warning if "G91 is present (but thats just to manage the MOVEMENT not the extrusion...)

if you have thoughts on this or suggestions let us know.
We'll do some research into the gvcode to see if there is a way we can do something like "hey I know you THINK you are at 0 extrusion, but trust me you're at 1171 (which would be a sensible thing to exist - like G92, I guess...) and we could add this into the PREP layer

**Comment by awe-source** [comment]
UPDATE 2:

According to the internet G92 will do exactly what you want (in theory).

if you add this line into the "NOMESH" bit... just before LAYER42 (around line 430)
it should fix it...
;*********
G92 E1171.0006    ; PROBABLY just whatever the LAST E in LAYER 41 is...
;*********

;TIME_ELAPSED:1384.446074
;LAYER:42
M117 INDICATOR-Layer42
;TYPE:WALL-INNER
;MESH:cap_mos_grand.3MF
G1 F3000 X-11.094 Y16.135 **E1171.74726** ; <-- shoudl only extrude difference between this and the number above

NOTE: if this work, please let us know and we can add it into the mix when we create the PREP layer, and detect a M82

**Comment by fabreu249PT** [comment]
Thanks for the suport, and nice idea for the plugin.
The model of the printer is Deltacomb DC-20.
The G92 i was talking, is the one of the following code (different file):
G1 X13.54 Y33.61 E4157.01814
G1 X13.377 Y33.666 E4157.02387
G1 X-14.602 Y33.681 **E4157.95446**  <--
G92 E0
G1 X-14.765 Y33.625 E0.00573
G1 X-14.956 Y33.484 E0.01363

Around the E4157 value, Cura use G92 to zero the extruder and start again, but depends on what i print not all the files has that much material to extrude, my solution was activate on cura relative extrusion, and that way, when need to resume the print, only extrudes (i think/hope), only extrudes what needed for that line.

**Comment by awe-source** [comment]
please experiment with latest version 0.1.5 as (I hope) it solves this issue (without causing new ones!)

**Comment by fabreu249PT** [comment]
I experiment and not extrudes a lot, in other words, the correction you made it works, the G92 on the previous line of Extruder "reset" the extruder and print normally
